export const SET_THEME = 'SET_THEME'
export const SET_INITIAL_ARRAY = 'SET_INITIAL_ARRAY'
export const SET_ALGORYTHM = 'SET_ALGORYTHM'
export const SET_SPEED = 'SET_SPEED'
export const SET_SIZE = 'SET_SIZE'